### ISSUE TITLE
ArrowData is an internal API of arrow, so its GetValues method shouldn't be used

### ISSUE THREAD

**Issue by FluorineDog** [zilliztech/arctern#119]
https://github.com/zilliztech/GIS/blob/ac7171a9d9f71bbb1e9a3d2d0499a9f79cdad651/cpp/src/arrow/render_api.cpp#L89

This code is broken at arrow 0.15
```
error: ‘using element_type = struct arrow::ArrayData’ {aka ‘struct arrow::ArrayData’} has no member named ‘GetValues’
   55 |   vertices_x_ = (uint32_t*)x_array->data()->GetValues<uint8_t>(1);
```

**Comment by nezha2017** [comment]
so if `GetValue` is not recommended, which method be used to ? @FluorineDog

**Comment by FluorineDog** [comment]
@nezha2017 we should use `x_array->value_data()->data()` or `x_array->value_data()->mutable_data()`
