### ISSUE TITLE
st_envelope_udf different result with postgis

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#145]
in our st_envelope_udf function the result will be 'POINT (0 0)'

actually, it's different on envelope all empty geometry types

postgis:
select st_astext(st_envelope('POLYGON EMPTY'::geometry));
result:
st_astext

POLYGON EMPTY

**Comment by nezha2017** [comment]
this bug had fixed on PT #136 , please update your arctern, and retry it @liangliu

**Comment by liangliu** [comment]
this issue is fixed and verified
