### ISSUE TITLE
st_issimple difference

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#148]
postgis
SELECT ST_isSimple('POLYGON ((1 2, 3 4, 5 6, 1 2))'::geometry);
result:
t (means true)

per actern, the result is false

**Comment by nezha2017** [comment]
I have tested in postgis, this sql prints `False` in my test, 

please update your postgis and test this sql again.

**Comment by liangliu** [comment]
this issue is verified while use postgis 3.0, version issue I guess.
