### ISSUE TITLE
st_isvalid difference

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#149]
in postgis:

select st_isvalid("POINT (30)");
select st_isvalid("POINT (,)");
select st_isvalid("POINT (a b)");
select st_isvalid("MULTIPOINT ()");
select st_isvalid("MULTIPOINT (,)");
select st_isvalid("POINT(1 2 3 4 5 6 7)");
select st_isvalid("LINESTRING(1 1)");
select st_isvalid("MULTIPOINT(1 1, 2 2");

all return ERROR while executing these in psql

in arctern, all of them return FALSE

**Comment by nezha2017** [comment]
I presume that 'return FALSE' is also reasonable, what's your opinion ? @GuoRentong @guoxiangzhou @liangliu

**Comment by liangliu** [comment]
the arctern results returned is OK in my thoughts, however it's just different with postgis results, if we accept that, it's fine.

**Comment by liangliu** [comment]
please let me know if you have diff options on this @GuoRentong @guoxiangzhou 
I'll close this issue if no comments given

**Comment by beautifulpython** [comment]
I think 'return parser error' for SQL and 'return false' for API are actually equivalent . But, I got some bad input case which return true in arctern.Please refer to #161

**Comment by liangliu** [comment]
close this issue
