### ISSUE TITLE
ST_IsValid bug and other function implementation related to IsValid

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/arctern#161]
I found some differences in arctern's parsing rules for WKT strings. Some data that would be reported incorrectly in postgis, but not arctern.

I tested the ST_IsValid function in arctern :
```python
def run_st_tmp(spark):
    register_funcs(spark)
    input = []

    input.extend([('POINT (1 8 2 4 )kdjff',)])
    input.extend([('POLYGON ((1 1,1 2,2 2,2 1,1 1)),((dkjfkjd0 0,1 -1,3 4,-2 3,0 0))',)])

    df = spark.createDataFrame(data=input, schema=['geos']).cache()
    df.createOrReplaceTempView("t1")
    spark.sql("select ST_IsValid_UDF(geos) from t1").show(100,0)
```
 I got the following results :
```
+--------------------+
|ST_IsValid_UDF(geos)|
+--------------------+
|    true            |
|    true            |
+--------------------+
```

Our ST_IsValid implementation, first call OGRGeometryFactory: : createFromWkt, but OGRGeometryFactory: : createFromWkt input check is weak, so it produce the correct results.

I also looked at the implementation of other functions.There is no IsValid check before calling the gdal API. Refer to the gdal website API documentation as follows:

` ` `
Geometry validity is not checked. In case you are unsure of the validity of the input geometries', call IsValid () before, otherwise the result took be wrong.

- refer to https://gdal.org/api/vector_c_api.html? Highlight = isvalid
` ` `

So here are two Suggestions:

- OGRGeometryFactory: : createFromWkt legitimacy examination and OGR_G_IsValid examination priority need to question
-  Gdal function is not responsible for the validity examination. Our other functions should do an IsValid check before calling the gdal C API.

**Comment by nezha2017** [comment]
this is the implementation of `ST_Valid`
```cpp
inline bool Wrapper_OGR_G_IsValid(const char* geo_wkt) {
  void* geo = nullptr;
  bool is_valid = false;
  auto err_code =
      OGRGeometryFactory::createFromWkt(geo_wkt, nullptr, (OGRGeometry**)(&geo));
  if (err_code == OGRERR_NONE) {
    is_valid = OGR_G_IsValid(geo) != 0;
  }
  if (geo) {
    OGRGeometryFactory::destroyGeometry((OGRGeometry*)geo);
  }
  return is_valid;
}
```
It has checked `IsValid()` after created.
So, It's the bug of `createFromWkt` not the `IsValid`.
```python
>>> from osgeo import ogr
>>> w1="POINT (1 8 2 4 )kdjff"
>>> w2="POLYGON ((1 1,1 2,2 2,2 1,1 1)),((dkjfkjd0 0,1 -1,3 4,-2 3,0 0))"
>>> p1=ogr.CreateGeometryFromWkt(w1)
>>> p2=ogr.CreateGeometryFromWkt(w2)
>>> p1.ExportToWkt()
'POINT (1 8 2)'
>>> p2.ExportToWkt()
'POLYGON ((1 1,1 2,2 2,2 1,1 1))'
>>> 
```

**Comment by nezha2017** [comment]
1. this [repo](https://github.com/antlr/grammars-v4/tree/master/wkt) provides antlr grammars for `WKT`
2. check input string before call `createFromWkt`
@bigsheeper
