### ISSUE TITLE
import zilliz_gis and zilliz_pyspark still failed

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#173]
commands:
conda install -c arctern-dev arctern-spark
conda install -c arctern-dev arctern
conda install -c arctern-dev libarctern

conda create -n arctern_dev -c nezha2017 -c conda-forge arctern
conda activate arctern_dev

enter python env and:
import zilliz_gis
import zilliz_pyspark

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'zilliz_gis'

**Comment by nezha2017** [comment]
use this command to creat new conda environment:
```bash 
conda create -n <env> -c arctern-dev -c conda-forge arctern-spark
```
