### ISSUE TITLE
ST_IsSimple bug

### ISSUE THREAD

**Issue by become-nice** [zilliztech/arctern#199]
I got different results (compared to postgis) when test st_issimple.

arctern test code :
***
def run_st_issimple(spark): 
   simple_df =spark.read.format('csv').option("header","false").option("delimiter","|").load("/home/liupeng/test_data/issimple.csv") 
   simple_df.createOrReplaceTempView("simple") 
   rs = spark.sql("select ST_IsSimple_UDF(_c0) from simple").collect() 
   for i in rs: 
   print (i)
***

postgis sql:
***
   create table test_table (geo1 geometry); 
   copy test_table from '/home/zilliz/liupeng_data/issimple.csv' with delimiter '|' ;
   select ST_IsSimple(geo1) from test_table;
***

arctern results:
***
   Row(ST_IsSimple_UDF(_c0)=True) 
   Row(ST_IsSimple_UDF(_c0)=True) 
   Row(ST_IsSimple_UDF(_c0)=True) 
   Row(ST_IsSimple_UDF(_c0)=True) 
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=False)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=False)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=False)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=False)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
   Row(ST_IsSimple_UDF(_c0)=True)
***

postgis results:
***
   st_issimple
   t
   t
   t
   t
   t
   t
   t
   t
   t
   t
   t
   t
   f
   t
   t
   t
   f
   t
   t
   t
   t
   t
   f
   t
   f
   t
   t
   t
   t
   t
   t
   t
***

test data:
***
   POINT EMPTY
   LINESTRING EMPTY
   POLYGON EMPTY
   MULTIPOINT EMPTY
   MULTILINESTRING EMPT
   MULTIPOLYGON EMPTY
   POINT (30 10)
   POLYGON ((30 10,40 40,20 40,10 20,30 10))
   POLYGON ((1 2,3 4,5 6,1 2))
   POLYGON ((1 1,3 1,3 3,1 3,1 1))
   POLYGON ((0 0,0 1,1 1,1 0,0 0),(0 1,1 1,1 2,0 2,0 1))
   POLYGON ((0 0,2 0,2 2,0 2,0 0),(1 0,3 0,3 2,1 2,1 0))
   LINESTRING (1 1,2 2,2 3.5,1 3,1 2,2 1)
   LINESTRING (0 0,0 2)
   LINESTRING (77.29 29.07,77.42 29.26,77.27 29.31,77.29 29.07)
   MULTIPOINT (1 2,2 3)
   MULTIPOINT (1 2,2 3,1 2,4 6)
   MULTILINESTRING ((1 1,1 2),(2 4,1 9,1 8))
   MULTILINESTRING ((1 1,1 2),(1 1,1 2))
   MULTIPOLYGON (((0 0,2 0,2 2,0 2,0 0)),((1 0,3 0,3 2,1 2,1 0)))
   MULTIPOLYGON (((0 0,4 0,4 4,0 4,0 0)),((1 8,2 8,2 9,1 9,1 8)),((6 6,6 12,12 12,12 6,6 6),(7 7,7 8,8 8,8 7,7 7)))
   CIRCULARSTRING (0 0,1 1,2 0)
   MULTICURVE((0 0,5 5),CIRCULARSTRING (4 0,4 4,8 4))
   MULTICURVE(CIRCULARSTRING (0 2,1 1,2 2),CIRCULARSTRING (0 0,1 1,2 0)) 
   COMPOUNDCURVE(CIRCULARSTRING (0 0,1 1,1 0),(1 0,-1 2)) 
   COMPOUNDCURVE(CIRCULARSTRING (2 0,3 3,3 0),(3 0,2 0))
   CURVEPOLYGON(CIRCULARSTRING (7 0,9 0,9 4,7 4,7 0),(7 0,9 0,8 2,7 0)) 
   CURVEPOLYGON(CIRCULARSTRING (7 0,9 0,9 4,7 4,7 0),(5 0,9 0,8 2,5 0)) 
   CURVEPOLYGON(CIRCULARSTRING (0 0,4 0,4 4,0 4,0 0),CIRCULARSTRING (0 0,1 0,1 1,0 1,0 0)) 
   CURVEPOLYGON(CIRCULARSTRING (0 0,4 0,4 4,0 4,0 0),CIRCULARSTRING (-1 0,0 0,0 1,-1 1,-1 0)) 
   MULTISURFACE(CURVEPOLYGON(CIRCULARSTRING(0 0,4 0,4 4,0 4,0 0),(1 1,3 3,3 1,1 1)),((7 5,11 7,8 5,7 5),(8 6,8.5 6,8 6.5,8 6)))
   MULTISURFACE(CURVEPOLYGON(CIRCULARSTRING(0 0,4 0,4 4,0 4,0 0),(-6 1,3 3,3 1,-6 1)),((7 5,11 7,8 5,7 5),(8 6,8.5 6,8 6.5,8 6)))
***

The geos those have different results:
***
   POLYGON ((1 2,3 4,5 6,1 2))
   MULTICURVE((0 0,5 5),CIRCULARSTRING (4 0,4 4,8 4))
***

**Comment by nezha2017** [comment]
for `POLYGON ((1 2,3 4,5 6,1 2))`,both `arctern` and `postgis` get `false`, please check your test code.

----

`arctern` test
```bash
>>> import arctern_gis
>>> import arctern_pyspark
>>> arctern_pyspark.register_funcs(spark)
>>> spark.sql("select st_issimple_udf('POLYGON ((1 2,3 4,5 6,1 2))')").show()
+--------------------------------------------+                                  
|ST_IsSimple_UDF(POLYGON ((1 2,3 4,5 6,1 2)))|
+--------------------------------------------+
|                                       false|
+--------------------------------------------+
```

----
`postgis` test
```bash
test=# select st_issimple(st_geomfromtext('POLYGON ((1 2,3 4,5 6,1 2))'));
 st_issimple 
-------------
 f
(1 row)
```

**Comment by nezha2017** [comment]
for input `MULTICURVE((0 0,5 5),CIRCULARSTRING (4 0,4 4,8 4))`, in postgis, it converts this input to `multilinestring`
```
MULTILINESTRING ((0.0000000000000000 0.0000000000000000, 5.0000000000000000 5.0000000000000000), (4.0000000000000000 0.0000000000000000, 3.9042737389348194 0.1005444362444907, 3.8135962659964848 0.2056648273147272, 3.7281860311597148 0.3151079289811611, 3.6482487951612823 0.4286100832257957, 3.5739771338043842 0.5458978534174395, 3.5055499740266578 0.6666886830445062, 3.4431321628495182 0.7906915764183986, 3.3868740702472468 0.9176077997076055, 3.3369112268925494 1.0471316006136768, 3.2933639976512947 1.1789509449552851, 3.2563372916130122 1.3127482683858989, 3.2259203093557050 1.4482012414341130, 3.2021863280538434 1.5849835460235768, 3.1851925249472353 1.7227656616018163, 3.1749798395960447 1.8612156589841187, 3.1715728752538097 1.9999999999999996, 3.1749798395960447 2.1387843410158807, 3.1851925249472348 2.2772343383981828, 3.2021863280538434 2.4150164539764227, 3.2259203093557050 2.5517987585658863, 3.2563372916130122 2.6872517316141007, 3.2933639976512943 2.8210490550447140, 3.3369112268925485 2.9528683993863214, 3.3868740702472464 3.0823922002923938, 3.4431321628495186 3.2093084235816018, 3.5055499740266574 3.3333113169554931, 3.5739771338043838 3.4541021465825601, 3.6482487951612819 3.5713899167742040, 3.7281860311597144 3.6848920710188384, 3.8135962659964844 3.7943351726852721, 3.9042737389348190 3.8994555637555091, 3.9999999999999996 4.0000000000000000, 4.1005444362444905 4.0957262610651810, 4.2056648273147283 4.1864037340035161, 4.3151079289811616 4.2718139688402861, 4.4286100832257960 4.3517512048387177, 4.5458978534174399 4.4260228661956162, 4.6666886830445060 4.4944500259733422, 4.7906915764183973 4.5568678371504809, 4.9176077997076044 4.6131259297527532, 5.0471316006136755 4.6630887731074502, 5.1789509449552851 4.7066360023487057, 5.3127482683858984 4.7436627083869878, 5.4482012414341128 4.7740796906442942, 5.5849835460235777 4.7978136719461570, 5.7227656616018177 4.8148074750527652, 5.8612156589841184 4.8250201604039553, 5.9999999999999991 4.8284271247461898, 6.1387843410158807 4.8250201604039553, 6.2772343383981815 4.8148074750527652, 6.4150164539764214 4.7978136719461570, 6.5517987585658863 4.7740796906442950, 6.6872517316141007 4.7436627083869878, 6.8210490550447140 4.7066360023487057, 6.9528683993863236 4.6630887731074502, 7.0823922002923947 4.6131259297527532, 7.2093084235816018 4.5568678371504818, 7.3333113169554931 4.4944500259733431, 7.4541021465825601 4.4260228661956162, 7.5713899167742031 4.3517512048387186, 7.6848920710188375 4.2718139688402861, 7.7943351726852708 4.1864037340035161, 7.8994555637555086 4.0957262610651810, 8.0000000000000000 4.0000000000000000))
```
then it check if this `multilinestring` is simple or not.
