### ISSUE TITLE
st_convexhull issue

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#200]
input data:
CIRCULARSTRING (0 2, -1 1,0 0, 0.5 0, 1 0, 2 1, 1 2, 0.5 2, 0 2)
COMPOUNDCURVE(CIRCULARSTRING(0 2, -1 1,0 0),(0 0, 0.5 0, 1 0),CIRCULARSTRING( 1 0, 2 1, 1 2),(1 2, 0.5 2, 0 2))

st_convexhull in arctern:
{"geos":"CURVEPOLYGON (COMPOUNDCURVE (CIRCULARSTRING (0 0,-1 1,0 2),(0 2,1 2),CIRCULARSTRING (1 2,2 1,1 0),(1 0,0 0)))"}
{"geos":"CURVEPOLYGON (COMPOUNDCURVE (CIRCULARSTRING (0 0,-1 1,0 2),(0 2,1 2),CIRCULARSTRING (1 2,2 1,1 0),(1 0,0 0)))"}

st_convexhull in postgis:
SELECT ST_AsText(ST_ConvexHull(ST_GeomFromText('CIRCULARSTRING (0 2, -1 1,0 0, 0.5 0, 1 0, 2 1, 1 2, 0.5 2, 0 2)')));
SELECT ST_AsText(ST_ConvexHull(ST_GeomFromText('COMPOUNDCURVE(CIRCULARSTRING(0 2, -1 1,0 0),(0 0, 0.5 0, 1 0),CIRCULARSTRING( 1 0, 2 1, 1 2),(1 2, 0.5 2, 0 2))')));

POLYGON((0 0,-0.049067674327418 0.001204543794828,-0.09801714032956 0.004815273327803,-0.146730474455361 0.010823490035219,-0.195090322016129 0.01921471959677,-0.242980179903264 0.0299687468
05456,-0.290284677254462 0.043059664267791,-0.336889853392221 0.05845593481698,-0.38268343236509 0.076120467488713,-0.427555093430282 0.096010706876557,-0.471396736825998 0.118078735651645,-0
.514102744193222 0.142271389999728,-0.555570233019602 0.168530387697455,-0.595699304492433 0.196792468519355,-0.634393284163645 0.226989546637263,-0.671558954847019 0.259048874645041,-0.70710
6781186548 0.292893218813453,-0.740951125354959 0.328441045152982,-0.773010453362737 0.365606715836355,-0.803207531480645 0.404300695507567,-0.831469612302545 0.444429766980398,-0.85772861000
0272 0.485897255806778,-0.881921264348355 0.528603263174002,-0.903989293123443 0.572444906569718,-0.923879532511287 0.61731656763491,-0.941544065183021 0.66311014660778,-0.956940335732209 0.7
09715322745538,-0.970031253194544 0.757019820096736,-0.98078528040323 0.804909677983872,-0.989176509964781 0.853269525544638,-0.995184726672197 0.901982859670439,-0.998795456205172 0.95093232
5672582,-1 1,-0.998795456205172 1.04906767432742,-0.995184726672197 1.09801714032956,-0.989176509964781 1.14673047445536,-0.98078528040323 1.19509032201613,-0.970031253194544 1.24298017990326
,-0.956940335732209 1.29028467725446,-0.941544065183021 1.33688985339222,-0.923879532511287 1.38268343236509,-0.903989293123443 1.42755509343028,-0.881921264348355 1.471396736826,-0.857728610
000272 1.51410274419322,-0.831469612302545 1.5555702330196,-0.803207531480645 1.59569930449243,-0.773010453362737 1.63439328416365,-0.740951125354959 1.67155895484702,-0.707106781186547 1.707
10678118655,-0.671558954847018 1.74095112535496,-0.634393284163645 1.77301045336274,-0.595699304492433 1.80320753148064,-0.555570233019602 1.83146961230255,-0.514102744193222 1.85772861000027...
POLYGON((0 0,-0.049067674327418 0.001204543794828,-0.09801714032956 0.004815273327803,-0.146730474455361 0.010823490035219,-0.195090322016129 0.01921471959677,-0.242980179903264 0.0299687468
05456,-0.290284677254462 0.043059664267791,-0.336889853392221 0.05845593481698,-0.38268343236509 0.076120467488713,-0.427555093430282 0.096010706876557,-0.471396736825998 0.118078735651645,-0
.514102744193222 0.142271389999728,-0.555570233019602 0.168530387697455,-0.595699304492433 0.196792468519355,-0.634393284163645 0.226989546637263,-0.671558954847019 0.259048874645041,-0.70710
6781186548 0.292893218813453,-0.740951125354959 0.328441045152982,-0.773010453362737 0.365606715836355,-0.803207531480645 0.404300695507567,-0.831469612302545 0.444429766980398,-0.85772861000
0272 0.485897255806778,-0.881921264348355 0.528603263174002,-0.903989293123443 0.572444906569718,-0.923879532511287 0.61731656763491,-0.941544065183021 0.66311014660778,-0.956940335732209 0.7
09715322745538,-0.970031253194544 0.757019820096736,-0.98078528040323 0.804909677983872,-0.989176509964781 0.853269525544638,-0.995184726672197 0.901982859670439,-0.998795456205172 0.95093232
5672582,-1 1,-0.998795456205172 1.04906767432742,-0.995184726672197 1.09801714032956,-0.989176509964781 1.14673047445536,-0.98078528040323 1.19509032201613,-0.970031253194544 1.24298017990326
,-0.956940335732209 1.29028467725446,-0.941544065183021 1.33688985339222,-0.923879532511287 1.38268343236509,-0.903989293123443 1.42755509343028,-0.881921264348355 1.471396736826,-0.857728610
000272 1.51410274419322,-0.831469612302545 1.5555702330196,-0.803207531480645 1.59569930449243,-0.773010453362737 1.63439328416365,-0.740951125354959 1.67155895484702,-0.707106781186547 1.707
10678118655,-0.671558954847018 1.74095112535496,-0.634393284163645 1.77301045336274,-0.595699304492433 1.80320753148064,-0.555570233019602 1.83146961230255,-0.514102744193222 1.85772861000027...

**Comment by nezha2017** [comment]
for `arctern`, try call `st_curvetoline` on `st_convexhull` for `circularstring` type, then compare with `postgis`

**Comment by liangliu** [comment]
close this issue
