### ISSUE TITLE
st_geomfromgeojson issue

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#201]
diff result while process EMPTY geometries on st_geomfromgeojson

arctern:

input:
{"type":"Point","coordinates":[]}
{"type":"LineString","coordinates":[]}

output:
{"geos":"POLYGON EMPTY"}
{"geos":"LINESTRING EMPTY"}

postgis:

{'type':'Point','coordinates':[]}
{'type':'LineString','coordinates':[]}

select st_astext(ST_GeomFromGeoJSON(geos)) from test_table;

result:
psql:test.sql:4: ERROR:  Too few ordinates in GeoJSON

**Comment by nezha2017** [comment]
it's ok, `arctern` could do more things than `postgis`.

**Comment by liangliu** [comment]
ok, close this issue
