### ISSUE TITLE
st_curvetoline issue

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#202]
input data:
geos
CIRCULARSTRING(0 0, 3 3, 0 0)
CIRCULARSTRING(0 0, 2 2, 4 0)
CIRCULARSTRING(0 0, 2 2, 4 4)
CIRCULARSTRING (0 2, -1 1,0 0, 0.5 0, 1 0, 2 1, 1 2, 0.5 2, 0 2)
COMPOUNDCURVE(CIRCULARSTRING(0 2, -1 1,0 0),(0 0, 0.5 0, 1 0),CIRCULARSTRING( 1 0, 2 1, 1 2),(1 2, 0.5 2, 0 2))

CIRCULARSTRING(0 0, 2 2, 4 4) -- same result for this

arctern:
{"geos":"LINESTRING (0 0,0.107060808154618 -0.099912625058362,0.22075960589941 -0.192200937862101,0.340554566684986 -0.276425142572847,0.465874812968849 -0.352183872499651,0.59612313670695 -0.419116102794078,0.730678845321904 -0.476902870898002,0.868900719585866 -0.525268796545475,1.01013006932203 -0.563983394075052,1.15369387236336 -0.59286217079898,1.29890798180992 -0.611767506194809,1.44508038629988 -0.620609307730007,1.59151450775943 -0.619345440193655,1.73751252091398 -0.607981926490169,1.88237867874381 -0.586572918937236,2.02542262803513 -0.555220441205478,2.16596269922763 -0.514073902129098,2.30332915488066 -0.463329383704845,2.43686738127656 -0.403228706671953,2.5659410079536 -0.33405827812615,2.68993494030087 -0.25614772665952,2.80825829076411 -0.169868331530068,2.92034719469439 -0.075631253346998,3.02566749741936 0.026114425296811,3.12371729973404 0.134883839907893,3.21402934967864 0.250158654692314,3.29617326920732 0.371389532661752,3.3697576051353 0.497998753474434,3.43443169459204 0.629382966535701,3.48988733608849 0.764916066238243,3.53586025823893 0.903952175640541,3.57213137913311 1.04582872436464,3.59852785036219 1.18986960604553,3.61492388072008 1.33538840028626,3.62124133565521 1.48169164376338,3.61745010961795 1.62808213489546,3.60356826952682 1.77386225632654,3.57966196867164 1.91833729939003,3.5458451314629 2.06081877471217,3.50227891052998 2.20062769317735,3.44917091875561 2.33709780162042,3.38677423990578 2.46957875782652,3.31538622257051 2.59743922970779,3.23534706316229 2.72006990388843,3.14703818472537 2.8368863893603,3.05088041928127 2.94733200237215,2.94733200237215 3.05088041928127,2.8368863893603 3.14703818472537,2.72006990388843 3.23534706316229,2.59743922970779 3.31538622257051,2.46957875782652 3.38677423990578,2.33709780162042 3.44917091875561,2.20062769317735 3.50227891052998,2.06081877471217 3.5458451314629,1.91833729939003 3.57966196867164,1.77386225632654 3.60356826952682,1.62808213489546 3.61745010961795,1.48169164376338 3.62124133565521,1.33538840028626 3.61492388072008,1.18986960604553 3.59852785036219,1.04582872436458 3.57213137913311,0.903952175640541 3.53586025823893,0.764916066238214 3.48988733608849,0.629382966535701 3.43443169459204,0.497998753474434 3.3697576051353,0.371389532661738 3.29617326920732,0.250158654692314 3.21402934967864,0.134883839907893 3.12371729973404,0.026114425296806 3.02566749741936,-0.075631253347002 2.92034719469439,-0.169868331530068 2.80825829076411,-0.256147726659535 2.68993494030087,-0.334058278126164 2.5659410079536,-0.403228706671953 2.43686738127656,-0.46332938370486 2.30332915488066,-0.514073902129098 2.16596269922763,-0.555220441205478 2.02542262803513,-0.586572918937236 1.88237867874375,-0.607981926490169 1.73751252091398,-0.619345440193655 1.59151450775937,-0.620609307730007 1.44508038629988,-0.611767506194809 1.29890798180986,-0.59286217079898 1.15369387236336,-0.563983394075052 1.01013006932203,-0.525268796545475 0.868900719585838,-0.476902870898002 0.730678845321904,-0.419116102794078 0.59612313670695,-0.352183872499651 0.465874812968835,-0.276425142572847 0.340554566684972,-0.192200937862097 0.220759605899399,-0.099912625058355 0.107060808154614,0 0)"}
{"geos":"LINESTRING (0 0,0.004871899480351 0.139512947488249,0.019463862516859 0.278346201920122,0.043704798532389 0.415823381635519,0.077476608123362 0.551274711634022,0.120614758428182 0.684040286651339,0.172909084714803 0.813473286151606,0.234104814282148 0.938943125571796,0.303903807687149 1.05983852846646,0.381966011250114 1.17557050458498,0.467911113762042 1.28557521937313,0.56132039932271 1.38931674091805,0.661738787282303 1.4862896509548,0.768677049348696 1.57602150721345,0.88161419305851 1.6580751451101,1.0 1.7320508075689,1.1232577064219 1.79758809259835,1.25078681316819 1.85436770913361,1.38196601125014 1.90211303259031,1.51615620880068 1.94059145255204,1.65270364466619 1.96961550602447,1.79094307346475 1.98904379073656,1.93020100659504 1.99878165403823,2.06979899340502 1.99878165403823,2.20905692653537 1.98904379073656,2.34729635533392 1.96961550602447,2.48384379119943 1.94059145255204,2.61803398874997 1.90211303259036,2.74921318683187 1.85436770913361,2.87674229357822 1.79758809259835,3.0 1.7320508075689,3.11838580694155 1.6580751451101,3.23132295065136 1.57602150721345,3.33826121271772 1.4862896509548,3.43867960067735 1.38931674091805,3.53208888623806 1.28557521937313,3.61803398874997 1.17557050458498,3.69609619231289 1.05983852846646,3.76589518571791 0.938943125571796,3.82709091528523 0.813473286151606,3.87938524157187 0.684040286651339,3.92252339187667 0.551274711634022,3.9562952014677 0.415823381635519,3.98053613748323 0.278346201920137,3.99512810051965 0.139512947488257,4 0)"}
{"geos":"LINESTRING (0 0,2 2,4 4)"}
{"geos":"LINESTRING (0 2,-0.069756473744128 1.99756405025983,-0.139173100960072 1.99026806874159,-0.20791169081776 1.97814760073385,-0.275637355817011 1.96126169593833,-0.342020143325669 1.93969262078593,-0.406736643075803 1.91354545764261,-0.469471562785898 1.88294759285895,-0.529919264233229 1.84804809615645,-0.587785252292491 1.80901699437499,-0.642787609686564 1.76604444311903,-0.694658370459024 1.71933980033867,-0.743144825477401 1.66913060635886,-0.788010753606727 1.61566147532568,-0.829037572555052 1.55919290347077,-0.866025403784448 1.5,-0.898794046299173 1.43837114678911,-0.927183854566806 1.37460659341593,-0.951056516295182 1.30901699437499,-0.970295726276021 1.24192189559972,-0.984807753012234 1.17364817766696,-0.99452189536828 1.10452846326768,-0.999390827019113 1.03489949670251,-0.999390827019113 0.965100503297521,-0.99452189536828 0.895471536732344,-0.984807753012234 0.826351822333095,-0.970295726276021 0.75807810440034,-0.951056516295154 0.690983005625071,-0.927183854566806 0.625393406584095,-0.898794046299173 0.561628853210948,-0.866025403784448 0.5,-0.829037572555052 0.440807096529255,-0.788010753606727 0.384338524674348,-0.743144825477401 0.330869393641151,-0.694658370458995 0.280660199661355,-0.642787609686564 0.233955556881021,-0.587785252292491 0.190983005625057,-0.529919264233229 0.151951903843575,-0.469471562785898 0.117052407141074,-0.406736643075803 0.086454542357398,-0.342020143325669 0.060307379214091,-0.275637355816997 0.038738304061681,-0.20791169081776 0.021852399266194,-0.139173100960065 0.009731931258429,-0.069756473744121 0.002435949740176,0 0,0.5 0.0,1 0,1.06975647374418 0.002435949740176,1.13917310096008 0.00973193125843,1.20791169081781 0.021852399266194,1.27563735581703 0.038738304061681,1.34202014332567 0.060307379214093,1.40673664307582 0.086454542357401,1.46947156278594 0.117052407141074,1.52991926423323 0.151951903843575,1.58778525229252 0.190983005625057,1.64278760968659 0.233955556881028,1.69465837045902 0.280660199661355,1.74314482547743 0.330869393641151,1.78801075360673 0.384338524674348,1.82903757255508 0.440807096529255,1.86602540378448 0.5,1.8987940462992 0.561628853210948,1.92718385456681 0.625393406584095,1.95105651629518 0.690983005625071,1.97029572627605 0.75807810440034,1.98480775301226 0.826351822333095,1.99452189536828 0.895471536732373,1.99939082701911 0.965100503297521,1.99939082701911 1.03489949670251,1.99452189536828 1.10452846326768,1.98480775301226 1.17364817766696,1.97029572627605 1.24192189559972,1.95105651629518 1.30901699437499,1.92718385456681 1.37460659341593,1.8987940462992 1.43837114678911,1.86602540378448 1.5,1.82903757255508 1.55919290347077,1.78801075360673 1.61566147532568,1.74314482547743 1.66913060635886,1.69465837045902 1.71933980033867,1.64278760968659 1.76604444311903,1.58778525229252 1.80901699437499,1.52991926423323 1.84804809615645,1.46947156278594 1.88294759285895,1.40673664307582 1.91354545764261,1.34202014332573 1.93969262078593,1.27563735581703 1.96126169593833,1.20791169081781 1.97814760073385,1.13917310096008 1.99026806874159,1.06975647374418 1.99756405025983,1 2,0.5 2.0,0 2)"}
{"geos":"LINESTRING (0 2,-0.069756473744128 1.99756405025983,-0.139173100960072 1.99026806874159,-0.20791169081776 1.97814760073385,-0.275637355817011 1.96126169593833,-0.342020143325669 1.93969262078593,-0.406736643075803 1.91354545764261,-0.469471562785898 1.88294759285895,-0.529919264233229 1.84804809615645,-0.587785252292491 1.80901699437499,-0.642787609686564 1.76604444311903,-0.694658370459024 1.71933980033867,-0.743144825477401 1.66913060635886,-0.788010753606727 1.61566147532568,-0.829037572555052 1.55919290347077,-0.866025403784448 1.5,-0.898794046299173 1.43837114678911,-0.927183854566806 1.37460659341593,-0.951056516295182 1.30901699437499,-0.970295726276021 1.24192189559972,-0.984807753012234 1.17364817766696,-0.99452189536828 1.10452846326768,-0.999390827019113 1.03489949670251,-0.999390827019113 0.965100503297521,-0.99452189536828 0.895471536732344,-0.984807753012234 0.826351822333095,-0.970295726276021 0.75807810440034,-0.951056516295154 0.690983005625071,-0.927183854566806 0.625393406584095,-0.898794046299173 0.561628853210948,-0.866025403784448 0.5,-0.829037572555052 0.440807096529255,-0.788010753606727 0.384338524674348,-0.743144825477401 0.330869393641151,-0.694658370458995 0.280660199661355,-0.642787609686564 0.233955556881021,-0.587785252292491 0.190983005625057,-0.529919264233229 0.151951903843575,-0.469471562785898 0.117052407141074,-0.406736643075803 0.086454542357398,-0.342020143325669 0.060307379214091,-0.275637355816997 0.038738304061681,-0.20791169081776 0.021852399266194,-0.139173100960065 0.009731931258429,-0.069756473744121 0.002435949740176,0 0,0.5 0.0,1 0,1.06975647374418 0.002435949740176,1.13917310096008 0.00973193125843,1.20791169081781 0.021852399266194,1.27563735581703 0.038738304061681,1.34202014332567 0.060307379214093,1.40673664307582 0.086454542357401,1.46947156278594 0.117052407141074,1.52991926423323 0.151951903843575,1.58778525229252 0.190983005625057,1.64278760968659 0.233955556881028,1.69465837045902 0.280660199661355,1.74314482547743 0.330869393641151,1.78801075360673 0.384338524674348,1.82903757255508 0.440807096529255,1.86602540378448 0.5,1.8987940462992 0.561628853210948,1.92718385456681 0.625393406584095,1.95105651629518 0.690983005625071,1.97029572627605 0.75807810440034,1.98480775301226 0.826351822333095,1.99452189536828 0.895471536732373,1.99939082701911 0.965100503297521,1.99939082701911 1.03489949670251,1.99452189536828 1.10452846326768,1.98480775301226 1.17364817766696,1.97029572627605 1.24192189559972,1.95105651629518 1.30901699437499,1.92718385456681 1.37460659341593,1.8987940462992 1.43837114678911,1.86602540378448 1.5,1.82903757255508 1.55919290347077,1.78801075360673 1.61566147532568,1.74314482547743 1.66913060635886,1.69465837045902 1.71933980033867,1.64278760968659 1.76604444311903,1.58778525229252 1.80901699437499,1.52991926423323 1.84804809615645,1.46947156278594 1.88294759285895,1.40673664307582 1.91354545764261,1.34202014332573 1.93969262078593,1.27563735581703 1.96126169593833,1.20791169081781 1.97814760073385,1.13917310096008 1.99026806874159,1.06975647374418 1.99756405025983,1 2,0.5 2.0,0 2)"}

postgis:
 LINESTRING(0 0,0.075408327183369 -0.071794695798885,0.154248620486046 -0.139802800502636,0.236330946735871 -0.203860476630214,0.321457562419347 -0.263813403629038,0.40942339006308 -0.319517149646712,0.50001651228338 -0.370837519480007,0.5930186823138 -0.417650877862861,0.688205849780705 -0.459844447314565,0.785348700460258 -0.497316579830588,0.884213208716464 -0.529977001761529,0.984561201289425 -0.557747031290241,1.08615093107559 -0.580559767983221,1.18873765951768 -0.598360253959617,1.29207424620136 -0.611105606289573,1.39591174423809 -0.618765120302966,1.5 -0.621320343559642,1.60408825576191 -0.618765120302966,1.70792575379864 -0.611105606289573,1.81126234048232 -0.598360253959617,1.91384906892441 -0.580559767983221,2.01543879871058 -0.557747031290241,2.11578679128354 -0.529977001761529,2.21465129953974 -0.497316579830588,2.3117941502193 -0.459844447314565,2.4069813176862 -0.417650877862861,2.49998348771662 -0.370837519480006,2.59057660993692 -0.319517149646712,2.67854243758065 -0.263813403629038,2.76366905326413 -0.203860476630214,2.84575137951395 -0.139802800502636,2.92459167281663 -0.071794695798886,3 0,3.07179469579889 0.075408327183369,3.13980280050264 0.154248620486046,3.20386047663021 0.236330946735871,3.26381340362904 0.321457562419347,3.31951714964671 0.40942339006308,3.37083751948001 0.50001651228338,3.41765087786286 0.593018682313799,3.45984444731456 0.688205849780705,3.49731657983059 0.785348700460258,3.52997700176153 0.884213208716464,3.55774703129024 0.984561201289424,3.58055976798322 1.08615093107559,3.59836025395962 1.18873765951768,3.61110560628957 1.29207424620136,3.61876512030297 1.39591174423809,3.62132034355964 1.5,3.61876512030297 1.60408825576191,3.61110560628957 1.70792575379864,3.59836025395962 1.81126234048232,3.58055976798322 1.91384906892441,3.55774703129024 2.01543879871058,3.52997700176153 2.11578679128354,3.49731657983059 2.21465129953974,3.45984444731456 2.3117941502193,3.41765087786286 2.4069813176862,3.37083751948001 2.49998348771662,3.31951714964671 2.59057660993692,3.26381340362904 2.67854243758065,3.20386047663021 2.76366905326413,3.13980280050264 2.84575137951395,3.07179469579889 2.92459167281663,3 3,2.92459167281663 3.07179469579889,2.84575137951395 3.13980280050264,2.76366905326413 3.20386047663021,2.67854243758065 3.26381340362904,2.59057660993692 3.31951714964671,2.49998348771662 3.37083751948001,2.4069813176862 3.41765087786286,2.3117941502193 3.45984444731456,2.21465129953974 3.49731657983059,2.11578679128354 3.52997700176153,2.01543879871058 3.55774703129024,1.91384906892441 3.58055976798322,1.81126234048232 3.59836025395962,1.70792575379864 3.61110560628957,1.60408825576191 3.61876512030297,1.5 3.62132034355964,1.39591174423809 3.61876512030297,1.29207424620136 3.61110560628957,1.18873765951768 3.59836025395962,1.08615093107559 3.58055976798322,0.984561201289425 3.55774703129024,0.884213208716464 3.52997700176153,0.785348700460259 3.49731657983059,0.688205849780706 3.45984444731457,0.593018682313799 3.41765087786286,0.50001651228338 3.37083751948001,0.40942339006308 3.31951714964671,0.321457562419347 3.26381340362904,0.236330946735872 3.20386047663021,0.154248620486045 3.13980280050264,0.075408327183369 3.07179469579889,0 3,-0.071794695798885 2.92459167281663,-0.139802800502635 2.84575137951396,-0.203860476630214 2.76366905326413,-0.263813403629038 2.67854243758065,-0.319517149646712 2.59057660993692,-0.370837519480006 2.49998348771662,-0.417650877862861 2.4069813176862,-0.459844447314565 2.31179415021929,-0.497316579830588 2.21465129953974,-0.529977001761529 2.11578679128354,-0.557747031290241 2.01543879871058,-0.580559767983221 1.91384906892442,-0.598360253959617 1.81126234048232,-0.611105606289573 1.70792575379864,-0.618765120302966 1.60408825576191,-0.621320343559642 1.5,-0.618765120302966 1.39591174423809,-0.611105606289573 1.29207424620136,-0.598360253959617 1.18873765951768,-0.580559767983221 1.08615093107559,-0.557747031290241 0.984561201289425,-0.529977001761529 0.884213208716465,-0.497316579830588 0.785348700460259,-0.459844447314565 0.688205849780706,-0.417650877862861 0.593018682313799,-0.370837519480007 0.50001651228338,-0.319517149646712 0.40942339006308,-0.263813403629038 0.321457562419347,-0.203860476630215 0.236330946735872,-0.139802800502636 0.154248620486045,0 0)
 LINESTRING(0 0,0.002409087589655 0.098135348654836,0.009630546655606 0.196034280659122,0.021646980070438 0.293460948910724,0.038429439193539 0.390180644032257,0.059937493610912 0.485960359806528,0.086119328535582 0.580569354508925,0.116911869633959 0.673779706784441,0.152240934977427 0.76536686473018,0.192021413753113 0.855110186860564,0.23615747130329 0.942793473651996,0.284542779999456 1.02820548838644,0.337060775394909 1.1111404660392,0.39358493703871 1.19139860898487,0.453979093274526 1.26878656832729,0.518097749290082 1.34311790969404,0.585786437626905 1.4142135623731,0.656882090305963 1.48190225070992,0.731213431672709 1.54602090672547,0.808601391015133 1.60641506296129,0.888859533960796 1.66293922460509,0.971794511613557 1.71545722000054,1.057206526348 1.76384252869671,1.14488981313944 1.80797858624689,1.23463313526982 1.84775906502257,1.32622029321556 1.88308813036604,1.41943064549108 1.91388067146442,1.51403964019347 1.94006250638909,1.60981935596774 1.96157056080646,1.70653905108928 1.97835301992956,1.80396571934088 1.99036945334439,1.90186465134516 1.99759091241034,2 2,2.09813534865484 1.99759091241034,2.19603428065912 1.99036945334439,2.29346094891072 1.97835301992956,2.39018064403226 1.96157056080646,2.48596035980653 1.94006250638909,2.58056935450892 1.91388067146442,2.67377970678444 1.88308813036604,2.76536686473018 1.84775906502257,2.85511018686056 1.80797858624689,2.942793473652 1.76384252869671,3.02820548838644 1.71545722000054,3.1111404660392 1.66293922460509,3.19139860898487 1.60641506296129,3.26878656832729 1.54602090672547,3.34311790969404 1.48190225070992,3.41421356237309 1.41421356237309,3.48190225070992 1.34311790969404,3.54602090672547 1.26878656832729,3.60641506296129 1.19139860898487,3.66293922460509 1.1111404660392,3.71545722000054 1.02820548838644,3.76384252869671 0.942793473651996,3.80797858624689 0.855110186860564,3.84775906502257 0.76536686473018,3.88308813036604 0.67377970678444,3.91388067146442 0.580569354508925,3.94006250638909 0.485960359806528,3.96157056080646 0.390180644032257,3.97835301992956 0.293460948910723,3.99036945334439 0.196034280659121,3.99759091241034 0.098135348654836,4 0)
 LINESTRING(0 0,2 2,4 4)
 LINESTRING(0 2,-0.049067674327418 1.99879545620517,-0.098017140329561 1.9951847266722,-0.146730474455362 1.98917650996478,-0.195090322016128 1.98078528040323,-0.242980179903264 1.97003125319454,-0.290284677254462 1.95694033573221,-0.33688985339222 1.94154406518302,-0.38268343236509 1.92387953251129,-0.427555093430282 1.90398929312344,-0.471396736825998 1.88192126434835,-0.514102744193222 1.85772861000027,-0.555570233019602 1.83146961230255,-0.595699304492433 1.80320753148064,-0.634393284163645 1.77301045336274,-0.671558954847018 1.74095112535496,-0.707106781186547 1.70710678118655,-0.740951125354959 1.67155895484702,-0.773010453362737 1.63439328416365,-0.803207531480645 1.59569930449243,-0.831469612302545 1.5555702330196,-0.857728610000272 1.51410274419322,-0.881921264348355 1.471396736826,-0.903989293123443 1.42755509343028,-0.923879532511287 1.38268343236509,-0.941544065183021 1.33688985339222,-0.956940335732209 1.29028467725446,-0.970031253194544 1.24298017990326,-0.98078528040323 1.19509032201613,-0.989176509964781 1.14673047445536,-0.995184726672197 1.09801714032956,-0.998795456205172 1.04906767432742,-1 1,-0.998795456205172 0.950932325672582,-0.995184726672197 0.901982859670439,-0.989176509964781 0.853269525544638,-0.98078528040323 0.804909677983872,-0.970031253194544 0.757019820096736,-0.956940335732209 0.709715322745538,-0.941544065183021 0.66311014660778,-0.923879532511287 0.61731656763491,-0.903989293123443 0.572444906569718,-0.881921264348355 0.528603263174002,-0.857728610000272 0.485897255806778,-0.831469612302545 0.444429766980398,-0.803207531480645 0.404300695507567,-0.773010453362737 0.365606715836355,-0.740951125354959 0.328441045152982,-0.707106781186548 0.292893218813453,-0.671558954847019 0.259048874645041,-0.634393284163645 0.226989546637263,-0.595699304492433 0.196792468519355,-0.555570233019602 0.168530387697455,-0.514102744193222 0.142271389999728,-0.471396736825998 0.118078735651645,-0.427555093430282 0.096010706876557,-0.38268343236509 0.076120467488713,-0.336889853392221 0.05845593481698,-0.290284677254462 0.043059664267791,-0.242980179903264 0.029968746805456,-0.195090322016129 0.01921471959677,-0.146730474455361 0.010823490035219,-0.09801714032956 0.004815273327803,-0.049067674327418 0.001204543794828,0 0,0.5 0,1 0,1.04906767432742 0.001204543794828,1.09801714032956 0.004815273327803,1.14673047445536 0.010823490035219,1.19509032201613 0.01921471959677,1.24298017990326 0.029968746805456,1.29028467725446 0.043059664267791,1.33688985339222 0.058455934816979,1.38268343236509 0.076120467488713,1.42755509343028 0.096010706876557,1.471396736826 0.118078735651645,1.51410274419322 0.142271389999728,1.5555702330196 0.168530387697455,1.59569930449243 0.196792468519355,1.63439328416365 0.226989546637263,1.67155895484702 0.259048874645041,1.70710678118655 0.292893218813453,1.74095112535496 0.328441045152982,1.77301045336274 0.365606715836355,1.80320753148064 0.404300695507567,1.83146961230255 0.444429766980398,1.85772861000027 0.485897255806778,1.88192126434835 0.528603263174002,1.90398929312344 0.572444906569718,1.92387953251129 0.61731656763491,1.94154406518302 0.66311014660778,1.95694033573221 0.709715322745538,1.97003125319454 0.757019820096736,1.98078528040323 0.804909677983872,1.98917650996478 0.853269525544638,1.9951847266722 0.901982859670439,1.99879545620517 0.950932325672582,2 1,1.99879545620517 1.04906767432742,1.9951847266722 1.09801714032956,1.98917650996478 1.14673047445536,1.98078528040323 1.19509032201613,1.97003125319454 1.24298017990326,1.95694033573221 1.29028467725446,1.94154406518302 1.33688985339222,1.92387953251129 1.38268343236509,1.90398929312344 1.42755509343028,1.88192126434835 1.471396736826,1.85772861000027 1.51410274419322,1.83146961230255 1.5555702330196,1.80320753148064 1.59569930449243,1.77301045336274 1.63439328416365,1.74095112535496 1.67155895484702,1.70710678118655 1.70710678118655,1.67155895484702 1.74095112535496,1.63439328416365 1.77301045336274,1.59569930449243 1.80320753148064,1.5555702330196 1.83146961230255,1.51410274419322 1.85772861000027,1.471396736826 1.88192126434835,1.42755509343028 1.90398929312344,1.38268343236509 1.92387953251129,1.33688985339222 1.94154406518302,1.29028467725446 1.95694033573221,1.24298017990326 1.97003125319454,1.19509032201613 1.98078528040323,1.14673047445536 1.98917650996478,1.09801714032956 1.9951847266722,1.04906767432742 1.99879545620517,1 2,0.5 2,0 2)
 LINESTRING(0 2,-0.049067674327418 1.99879545620517,-0.098017140329561 1.9951847266722,-0.146730474455362 1.98917650996478,-0.195090322016128 1.98078528040323,-0.242980179903264 1.97003125319454,-0.290284677254462 1.95694033573221,-0.33688985339222 1.94154406518302,-0.38268343236509 1.92387953251129,-0.427555093430282 1.90398929312344,-0.471396736825998 1.88192126434835,-0.514102744193222 1.85772861000027,-0.555570233019602 1.83146961230255,-0.595699304492433 1.80320753148064,-0.634393284163645 1.77301045336274,-0.671558954847018 1.74095112535496,-0.707106781186547 1.70710678118655,-0.740951125354959 1.67155895484702,-0.773010453362737 1.63439328416365,-0.803207531480645 1.59569930449243,-0.831469612302545 1.5555702330196,-0.857728610000272 1.51410274419322,-0.881921264348355 1.471396736826,-0.903989293123443 1.42755509343028,-0.923879532511287 1.38268343236509,-0.941544065183021 1.33688985339222,-0.956940335732209 1.29028467725446,-0.970031253194544 1.24298017990326,-0.98078528040323 1.19509032201613,-0.989176509964781 1.14673047445536,-0.995184726672197 1.09801714032956,-0.998795456205172 1.04906767432742,-1 1,-0.998795456205172 0.950932325672582,-0.995184726672197 0.901982859670439,-0.989176509964781 0.853269525544638,-0.98078528040323 0.804909677983872,-0.970031253194544 0.757019820096736,-0.956940335732209 0.709715322745538,-0.941544065183021 0.66311014660778,-0.923879532511287 0.61731656763491,-0.903989293123443 0.572444906569718,-0.881921264348355 0.528603263174002,-0.857728610000272 0.485897255806778,-0.831469612302545 0.444429766980398,-0.803207531480645 0.404300695507567,-0.773010453362737 0.365606715836355,-0.740951125354959 0.328441045152982,-0.707106781186548 0.292893218813453,-0.671558954847019 0.259048874645041,-0.634393284163645 0.226989546637263,-0.595699304492433 0.196792468519355,-0.555570233019602 0.168530387697455,-0.514102744193222 0.142271389999728,-0.471396736825998 0.118078735651645,-0.427555093430282 0.096010706876557,-0.38268343236509 0.076120467488713,-0.336889853392221 0.05845593481698,-0.290284677254462 0.043059664267791,-0.242980179903264 0.029968746805456,-0.195090322016129 0.01921471959677,-0.146730474455361 0.010823490035219,-0.09801714032956 0.004815273327803,-0.049067674327418 0.001204543794828,0 0,0.5 0,1 0,1.04906767432742 0.001204543794828,1.09801714032956 0.004815273327803,1.14673047445536 0.010823490035219,1.19509032201613 0.01921471959677,1.24298017990326 0.029968746805456,1.29028467725446 0.043059664267791,1.33688985339222 0.058455934816979,1.38268343236509 0.076120467488713,1.42755509343028 0.096010706876557,1.471396736826 0.118078735651645,1.51410274419322 0.142271389999728,1.5555702330196 0.168530387697455,1.59569930449243 0.196792468519355,1.63439328416365 0.226989546637263,1.67155895484702 0.259048874645041,1.70710678118655 0.292893218813453,1.74095112535496 0.328441045152982,1.77301045336274 0.365606715836355,1.80320753148064 0.404300695507567,1.83146961230255 0.444429766980398,1.85772861000027 0.485897255806778,1.88192126434835 0.528603263174002,1.90398929312344 0.572444906569718,1.92387953251129 0.61731656763491,1.94154406518302 0.66311014660778,1.95694033573221 0.709715322745538,1.97003125319454 0.757019820096736,1.98078528040323 0.804909677983872,1.98917650996478 0.853269525544638,1.9951847266722 0.901982859670439,1.99879545620517 0.950932325672582,2 1,1.99879545620517 1.04906767432742,1.9951847266722 1.09801714032956,1.98917650996478 1.14673047445536,1.98078528040323 1.19509032201613,1.97003125319454 1.24298017990326,1.95694033573221 1.29028467725446,1.94154406518302 1.33688985339222,1.92387953251129 1.38268343236509,1.90398929312344 1.42755509343028,1.88192126434835 1.471396736826,1.85772861000027 1.51410274419322,1.83146961230255 1.5555702330196,1.80320753148064 1.59569930449243,1.77301045336274 1.63439328416365,1.74095112535496 1.67155895484702,1.70710678118655 1.70710678118655,1.67155895484702 1.74095112535496,1.63439328416365 1.77301045336274,1.59569930449243 1.80320753148064,1.5555702330196 1.83146961230255,1.51410274419322 1.85772861000027,1.471396736826 1.88192126434835,1.42755509343028 1.90398929312344,1.38268343236509 1.92387953251129,1.33688985339222 1.94154406518302,1.29028467725446 1.95694033573221,1.24298017990326 1.97003125319454,1.19509032201613 1.98078528040323,1.14673047445536 1.98917650996478,1.09801714032956 1.9951847266722,1.04906767432742 1.99879545620517,1 2,0.5 2,0 2)

**Comment by nezha2017** [comment]
for `st_curvetoline`, It is hard to get every points in `arctern` are equal to the points in `postgis`. In this case, I suggest `plot` the `wkt`, and compare if the two figure are similar.

**Comment by liangliu** [comment]
close this, make new function to compare this
