### ISSUE TITLE
st_crosses issue

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#210]
input data:
LINESTRING (1 1,1 2,2 3)|COMPOUNDCURVE(CIRCULARSTRING(0 0, 1 1, 1 0),(1 0, 0 1))

CIRCULARSTRING (0 2, -1 1, 0 2)|COMPOUNDCURVE(CIRCULARSTRING(0 0, 1 1, 1 0),(1 0, 0 1))

arctern:
select st_crosses_udf(left, right) as geos from test_crosses

ouput:
true
false

postgis:
select st_crosses('LINESTRING (1 1,1 2,2 3,1 1)'::geometry, 'COMPOUNDCURVE(CIRCULARSTRING(0 0, 1 1, 1 0),(1 0, 0 1))'::gemetry);
select st_crosses('CIRCULARSTRING (0 2, -1 1, 0 2)'::geometry, 'COMPOUNDCURVE(CIRCULARSTRING(0 0, 1 1, 1 0),(1 0, 0 1))'::geometry);

output:
f(false)
t(true)

**Comment by nezha2017** [comment]
for test data `LINESTRING (1 1,1 2,2 3)|COMPOUNDCURVE(CIRCULARSTRING(0 0, 1 1, 1 0),(1 0, 0 1))`, since `point(1 1)` is the intersection of these two geometries, so I believe this is the bug of postgis.

**Comment by liangliu** [comment]
close this issue
