### ISSUE TITLE
issimple curve issue

### ISSUE THREAD

**Issue by liangliu** [zilliztech/arctern#253]
MULTICURVE(CIRCULARSTRING (0 2,1 1,2 2),CIRCULARSTRING (0 0,1 1,2 0))

arctern
select st_issimple_udf(geos) from test_issimple

result
False

postgis
select st_issimple('MULTICURVE(CIRCULARSTRING (0 2,1 1,2 2),CIRCULARSTRING (0 0,1 1,2 0))'::geometry);

result
True

**Comment by nezha2017** [comment]
geometry `CIRCULARSTRING (0 2,1 1,2 2)` and `CIRCULARSTRING (0 0,1 1,2 0)` both include `point(1 1)`, so this geometry is not simple, so, This is the bug of `postgis`

**Comment by liangliu** [comment]
side issue, close this
