### ISSUE TITLE
In vega_choroplethmap, when  parameter color_style is "skyblue_to_white", the result is wrong.

### ISSUE THREAD

**Issue by xiaocai2333** [zilliztech/arctern#342]
egs:

vega_4 = vega_choroplethmap(1900, 1410, [-73.994092, 40.753893, -73.977588, 40.759642], "skyblue_to_white", [2.5, 5], 1.0, 'EPSG:4326')

output:
![image](https://user-images.githubusercontent.com/46207236/77291000-5b805080-6d18-11ea-9b6f-ab8dbaa7e929.png)

**Comment by xge-zilliz** [comment]
the issue has been resolved by pr#352
