### ISSUE TITLE
vega_choroplethmap：  When the width or height of the picture is less than or equal to 255, the result is wrong.

### ISSUE THREAD

**Issue by xiaocai2333** [zilliztech/arctern#345]
data: file 0_10000_nyc_taxi_and_building.csv is from file 0_5M_nyc_taxi_and_building.csv first 10000 lines
eg:
1. when width less than or equal 255,but height more than 255:

vega_1 = vega_choroplethmap(255, 256, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5], 1.0, 'EPSG:4326')
or
vega_1 = vega_choroplethmap(200, 256, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5], 1.0, 'EPSG:4326')

the output is same:
![image](https://user-images.githubusercontent.com/46207236/77297010-9dfb5a80-6d23-11ea-9342-6d973cf36889.png)

2. when width more than or equal 255,but height less than 255:

vega_1 = vega_choroplethmap(256, 255, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5], 1.0, 'EPSG:4326')
or
vega_1 = vega_choroplethmap(256, 200, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5], 1.0, 'EPSG:4326')

output:
![image](https://user-images.githubusercontent.com/46207236/77297350-15c98500-6d24-11ea-862b-0a14f0f893e2.png)

3. when width and height all less than or equal 255:

vega_1 = vega_choroplethmap(255, 255, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5], 1.0, 'EPSG:4326')
or
vega_1 = vega_choroplethmap(255, 200, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5], 1.0, 'EPSG:4326')
or
vega_1 = vega_choroplethmap(200, 255, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5], 1.0, 'EPSG:4326')

output:
![image](https://user-images.githubusercontent.com/46207236/77297641-8ffa0980-6d24-11ea-9c3f-a5be5feaa870.png)

4.when width and height all more than 255, the result seems is right.

vega_1 = vega_choroplethmap(256, 256, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5],1.0, 'EPSG:4326')
or
vega_1 = vega_choroplethmap(1000, 1000, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5], 1.0, 'EPSG:4326')
or
vega_1 = vega_choroplethmap(1900, 1410, [-73.994092, 40.753893, -73.977588, 40.759642], "blue_to_red", [2.5, 5],  1.0, 'EPSG:4326')

output:
![image](https://user-images.githubusercontent.com/46207236/77297911-f5e69100-6d24-11ea-83e5-002357c7d71f.png)

**Comment by xge-zilliz** [comment]
The issue has been resolved by pr #364
