### ISSUE TITLE
draw_weighted_point_map not supported yet

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#387]
`{
  id: "1",
  query: {
    sql:
      "SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS color FROM global_temp.nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), 'POLYGON ((-74.18426924298693 40.71314557388712, -74.18426924298693 40.783028338446684, -73.79942363522697 40.783028338446684, -73.79942363522697 40.71314557388712, -74.18426924298693 40.71314557388712))')) LIMIT 1000000",
    type: "point",
    params: {
      width: 776,
      height: 186,
      bounding_box: [
        -73.79942363522697,
        40.783028338446684,
        -74.18426924298693,
        40.71314557388712
      ],
      coordinate: "EPSG:4326",
      stroke_width: 3,
      stroke: "blue_green_yellow",
      opacity: 0.5
    }
  }
};`

**Comment by DragonDriver** [comment]
resolved by [pr397](https://github.com/zilliztech/arctern/pull/397)
