### ISSUE TITLE
PointMap receive server error when no point in BoundBox

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#388]
should return empty image instead

**Comment by talentAN** [comment]
query: {
    sql:
      "SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point FROM global_temp.nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), 'POLYGON ((-74.49301110068876 40.30527260555485, -74.49301110068876 40.46429049848476, -74.30020321883836 40.46429049848476, -74.30020321883836 40.30527260555485, -74.49301110068876 40.30527260555485))')) LIMIT 1000000",
    type: "point",
    params: {
      width: 580,
      height: 634,
      point: {
        bounding_box: [
          -74.49301110068876,
          40.30527260555485,
          -74.30020321883836,
          40.46429049848476
        ],
        coordinate: "EPSG:4326",
        stroke_width: 3,
        stroke: "#37A2DA",
        opacity: 0.5
      }
    }
  }
}

**Comment by bigsheeper** [comment]
**When the spark dataframe is empty, the pandas GROUPED AGG UDF won't be called. Here is the test program I write:**
```
from __future__ import print_function
 
import numpy as np
import pandas as pd
 
from pyspark.sql import SparkSession
from pyspark.sql.utils import require_minimum_pandas_version, require_minimum_pyarrow_version
from pyspark.sql.functions import col, lit, pandas_udf, struct, PandasUDFType, udf, DataType
from pyspark.sql.types import *
 
require_minimum_pandas_version()
require_minimum_pyarrow_version()

def test_null_df(df):
    @pandas_udf("string", PandasUDFType.GROUPED_AGG)
    def func(point):
        print("get here")
        return "res"

    df = df.coalesce(1)
    df.show()
    print(df['point'])
    hex_data = df.agg(func(df['point']))
    hex_data.show()

 
if __name__ == "__main__":
    spark = SparkSession \
        .builder \
        .appName("pandas_udf test") \
        .getOrCreate()
 
    spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")

    points_data = []
    for i in range(100):
        points_data.extend([("a",)])
    df = spark.createDataFrame(data = points_data, schema = ["point"])
    df.createOrReplaceTempView("df")
    df = spark.sql("select * from df where point != 'a'")

    test_null_df(df)
    spark.stop()
```
**And the result is that the "get here" message in UDF not print. So when the points is empty after `ST_Within` called, UDF `pointmap_wkb` won't be called, then the `df.collect()[0][0]` operation would cause the IndexOutOfRange error**
