### ISSUE TITLE
st_within not support "point (nan nan)" in cpu version

### ISSUE THREAD

**Issue by xiaocai2333** [zilliztech/arctern#401]
eg:
  auto l24 = "POINT (nan nan)";

  arrow::StringBuilder builder1;
  std::shared_ptr<arrow::Array> input1;
  builder1.Append(std::string(l24));

  builder1.Finish(&input1);

  auto r24 = "POLYGON ((0 0, 4 0, 4 4, 0 4, 0 0))";
  arrow::StringBuilder builder2;
  std::shared_ptr<arrow::Array> input2;

  builder2.Append(std::string(r24));
  builder2.Finish(&input2);

  auto res = arctern::gis::ST_Within(input1, input2);
  auto res_bool = std::static_pointer_cast<arrow::BooleanArray>(res);

output:
unknown file: Failure
C++ exception with description "gdal error code = 5" thrown in the test body.

**Comment by nezha2017** [comment]
"POINT (NaN Nan)" is not valid wkt
```python
from osgeo import ogr
w1="POINT (NaN Nan)"
p1=ogr.CreateGeometryFromWkt(w1)
ERROR 5: OGR Error: Corrupt data
```
@xiaocai2333
