### ISSUE TITLE
Gui Extract Sql

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#406]
"SELECT **hour**(tpep_dropoff_datetime) AS a, count(*) AS width FROM global_temp.nyc_taxi GROUP BY a LIMIT 10" works well, 

which word should use if I want to get the day of the week ? 

PS:In Megawise the word is "isodow"

**Comment by nezha2017** [comment]
for `isodow`, `date_formate(timestamp_cols, 'e')`
