### ISSUE TITLE
failed on ST_Within when input has empty wkt string

### ISSUE THREAD

**Issue by xge-zilliz** [zilliztech/arctern#413]
Some rows of column buildingtext_dropoff are empty strings,so:
failed on sql:
df = spark.sql("select buildingtext_dropoff as wkt, passenger_count as w from nyc_taxi where ST_Within(buildingtext_dropoff,'POLYGON ((-73.998427 40.730309, -73.954348 40.730309, -73.954348 40.780816 ,-73.998427 40.780816, -73.998427 40.730309))')")

success on sql
df = spark.sql("select buildingtext_dropoff as wkt, passenger_count as w from nyc_taxi where (buildingtext_dropoff != '' AND ST_Within(buildingtext_dropoff,'POLYGON ((-73.998427 40.730309, -73.954348 40.730309, -73.954348 40.780816 ,-73.998427 40.780816, -73.998427 40.730309))'))")

**Comment by nezha2017** [comment]
this is fixed on `wkb`,and the `sql` should rewrite like this
```sql
df = spark.sql("select buildingtext_dropoff as wkt, passenger_count as w from nyc_taxi where ST_Within(st_geomfromtext( buildingtext_dropoff),st_geomfromtext( 'POLYGON ((-73.998427 40.730309, -73.954348 40.730309, -73.954348 40.780816 ,-73.998427 40.780816, -73.998427 40.730309))'))")
```
if input is empty string, like `""`, `st_geomfromtext` will return `null`
