### ISSUE TITLE
trunc(tpep_dropoff_datetime, 'hour')  bug

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#466]
sql: "SELECT trunc(tpep_dropoff_datetime, 'hour') AS x, count(*) AS countval FROM nyc_taxi WHERE ((fare_amount BETWEEN 2.5 AND 18.958333333333332)) GROUP BY x ORDER BY x"

return only countval , without x

trunc(tpep_dropoff_datetime, 'week')
trunc(tpep_dropoff_datetime, 'day')  both works well

**Comment by xge-zilliz** [comment]
//year,month,day/dayofmonth,hour,minute,second
Examples:> SELECT day('2009-07-30'); 30 @talentAN

**Comment by nezha2017** [comment]
convert to unix time,and operator on this unix time, then return the timestamp, this is the sample sql
```sql
>>> spark.sql("select from_unixtime(unix_timestamp(t1)-(mod(unix_timestamp(t1),3600) ) ) ,t1  from d1").show()
+------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
|from_unixtime((unix_timestamp(t1, uuuu-MM-dd HH:mm:ss) - (unix_timestamp(t1, uuuu-MM-dd HH:mm:ss) % CAST(3600 AS BIGINT))), uuuu-MM-dd HH:mm:ss)|                 t1|
+------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
|                                                                                                                             2020-04-13 14:00:00|2020-04-13 14:15:16|
+------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+

```

**Comment by talentAN** [comment]
> convert to unix time,and operator on this unix time, then return the timestamp, this is the sample sql
> 
> ```sql
> >>> spark.sql("select from_unixtime(unix_timestamp(t1)-(mod(unix_timestamp(t1),3600) ) ) ,t1  from d1").show()
> +------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
> |from_unixtime((unix_timestamp(t1, uuuu-MM-dd HH:mm:ss) - (unix_timestamp(t1, uuuu-MM-dd HH:mm:ss) % CAST(3600 AS BIGINT))), uuuu-MM-dd HH:mm:ss)|                 t1|
> +------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
> |                                                                                                                             2020-04-13 14:00:00|2020-04-13 14:15:16|
> +------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
> ```

work well
