### ISSUE TITLE
PointMap Hover 没有点

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#468]
![image](https://user-images.githubusercontent.com/17634030/78970644-60c50400-7b3c-11ea-8b54-023ea666eb62.png)

**Comment by xge-zilliz** [comment]
The correct sql is like this: 
"SELECT * FROM nyc_taxi where ST_Distance (ST_Transform(ST_GeomFromText('point(-73.98743329651164 40.74172095432982)'), 'epsg:4326', 'epsg:3857'), ST_Transform(ST_GeomFromText('point(-73.98743329651164 40.74172095432982)'), 'epsg:4326', 'epsg:3857')) < 3809429357141503 limit 1"

**Comment by talentAN** [comment]
> The correct sql is like this:
> "SELECT * FROM nyc_taxi where ST_Distance (ST_Transform(ST_GeomFromText('point(-73.98743329651164 40.74172095432982)'), 'epsg:4326', 'epsg:3857'), ST_Transform(ST_GeomFromText('point(-73.98743329651164 40.74172095432982)'), 'epsg:4326', 'epsg:3857')) < 3809429357141503 limit 1"

"select *  from nyc_taxi where ST_Distance (ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform( 'point(-73.98577165457594 40.75299767312461)', 'epsg:4326', 'epsg:3857')) < 25.603425741334025   limit 1"

**Comment by xge-zilliz** [comment]
"select * from nyc_taxi where ST_Distance (ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform(ST_GeomFromText('point(-73.98577165457594 40.75299767312461)'), 'epsg:4326', 'epsg:3857')) < 25.603425741334025 limit 1"

**Comment by talentAN** [comment]
select *  from nyc_taxi where st_distance(st_transform(st_geomFromText('point(dropoff_longitude dropoff_latitude)'),'epsg:4326', 'epsg:3857'),st_transform(st_geomFromText ('point(-73.9813892027485 40.749567933132255)'),'epsg:4326', 'epsg:3857')) < 2.639846149574804   limit 1

still not work

**Comment by xge-zilliz** [comment]
> select * from nyc_taxi where st_distance(st_transform(st_geomFromText('point(dropoff_longitude dropoff_latitude)'),'epsg:4326', 'epsg:3857'),st_transform(st_geomFromText ('point(-73.9813892027485 40.749567933132255)'),'epsg:4326', 'epsg:3857')) < 2.639846149574804 limit 1
> 
> still not work

select * from nyc_taxi where ST_Distance(ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform(ST_GeomFromText ('point(-73.9813892027485 40.749567933132255)'),'epsg:4326', 'epsg:3857')) < 263.9846149574804 limit 1

**Comment by talentAN** [comment]
> > select * from nyc_taxi where st_distance(st_transform(st_geomFromText('point(dropoff_longitude dropoff_latitude)'),'epsg:4326', 'epsg:3857'),st_transform(st_geomFromText ('point(-73.9813892027485 40.749567933132255)'),'epsg:4326', 'epsg:3857')) < 2.639846149574804 limit 1
> > still not work
> 
> select * from nyc_taxi where ST_Distance(ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude), 'epsg:4326', 'epsg:3857'), ST_Transform(ST_GeomFromText ('point(-73.9813892027485 40.749567933132255)'),'epsg:4326', 'epsg:3857')) < 263.9846149574804 limit 1

select * from nyc_taxi where ST_Distance(ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude),'epsg:4326', 'epsg:3857'),st_transform(st_geomFromText ('point(-73.98062412194643 40.7556966380495)'),'epsg:4326', 'epsg:3857')) < 51.83817657829691   limit 1 报错
