### ISSUE TITLE
ChoroplethMap Render Wrong

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#469]
![image](https://user-images.githubusercontent.com/17634030/78974003-93bec600-7b43-11ea-8d8d-2f75cd2e3cd9.png)

**Comment by talentAN** [comment]
SELECT ST_GeomFromText(buildingtext_dropoff) AS wkt, avg(fare_amount) AS w FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-73.5 40.1, -73.5 41.1, -70.5 41.1, -70.5 40.1, -73.5 40.1))'))) AND ((buildingtext_dropoff!='')) GROUP BY wkt

**Comment by cxie** [comment]
hope this is the last time I saw you write Chinese



Best,
Starlord
Founder&nbsp;&amp;&nbsp;CEO,&nbsp;Zilliz


------------------ Original ------------------

**Comment by talentAN** [comment]
"SELECT ST_GeomFromText(buildingtext_dropoff) AS wkt, avg(total_amount) AS w FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-279.9892503268887 4.759749350803787, -279.9892503268887 54.89968974028662, 70.0953371208993 54.89968974028662, 70.0953371208993 4.759749350803787, -279.9892503268887 4.759749350803787))'))) AND ((buildingtext_dropoff!='')) GROUP BY wkt"

![image](https://user-images.githubusercontent.com/17634030/78984094-09cd2800-7b58-11ea-8e5d-e65aba74a639.png)

**Comment by xge-zilliz** [comment]
please post restful sql @talentAN

**Comment by bigsheeper** [comment]
There are a few problems in your requests:
1. Width and height in query params can only be integer type
2. We only support hex color string yet, such as '#00FF00'
3. Size of color gradient array can only be 1 or 2, size 3 is illegal

Here is a correct json after fixing problems above:
```
{
    "id": "xxxx",
    "query": {
        "sql": "SELECT ST_GeomFromText(buildingtext_dropoff) AS wkt, avg(total_amount) AS w FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-279.9892503268887 4.759749350803787, -279.9892503268887 54.89968974028662, 70.0953371208993 54.89968974028662, 70.0953371208993 4.759749350803787, -279.9892503268887 4.759749350803787))'))) AND ((buildingtext_dropoff!='')) GROUP BY wkt",
        "type": "choropleth",
        "params": {
            "width": 1825,
            "height": 318,
            "choropleth": {
                "bounding_box": [-279.9892503268887, 4.759749350803787, 70.0953371208993, 54.89968974028662],
                "color_gradient": ["#FF0000", "#00FF00"],
                "color_bound": [2.5, 75.08],
                "opacity": 1.0,
                "coordinate_system": "EPSG:4326",
                "aggregation_type": "avg"
            }
        }
    }
}
```
