### ISSUE TITLE
Weighted Map Rending wrong

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#474]
SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, fare_amount AS color FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-74.13392158802485 40.7483303472585, -74.13392158802485 40.7789373777718, -73.79090526061026 40.7789373777718, -73.79090526061026 40.7483303472585, -74.13392158802485 40.7483303472585))'))) LIMIT 1000000

![image](https://user-images.githubusercontent.com/17634030/78983295-8c54e800-7b56-11ea-85d6-d888bc14fcbc.png)

**Comment by cxie** [comment]
can you wtite in english please？！



Best,
Starlord
Founder&nbsp;&amp;&nbsp;CEO,&nbsp;Zilliz


------------------ Original ------------------

**Comment by xge-zilliz** [comment]
color_gradient does not support three parameters @talentAN
