### ISSUE TITLE
HeatMap render fail

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#482]
{"id":"b19f588a7d4e11eaacd30242ac110006","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, avg(total_amount) AS w FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-94.55232097143656 19.211495627778902, -94.55232097143656 56.98325825991088, -53.33161784643667 56.98325825991088, -53.33161784643667 19.211495627778902, -94.55232097143656 19.211495627778902))'))) GROUP BY point","type":"heat","params":{"width":938,"height":1139,"heat":{"bounding_box":[-94.55232097143656,19.211495627778902,-53.33161784643667,56.98325825991088],"coordinate_system":"EPSG:4326","map_zoom_level":4,"aggregation_type":"avg"}}}}

**Comment by talentAN** [comment]
Reshow

{
params: {
    heat: {
        aggregation_type: "avg",
        bounding_box: [-74.1079323964245, 40.678409429728276, -73.86984759334479, 40.83475563136591],
        coordinate_system: "EPSG:4326",
        map_zoom_level: 11.923152738875428,
        height: 1139,
        width: 1315,
    }
sql: "SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, avg(fare_amount) AS w FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-74.1079323964245 40.678409429728276, -74.1079323964245 40.83475563136591, -73.86984759334479 40.83475563136591, -73.86984759334479 40.678409429728276, -74.1079323964245 40.678409429728276))'))) GROUP BY point",
type: "heat"
}

**Comment by bigsheeper** [comment]
Your server version is too old, this issue has been fixed by updating gui/server.

**Comment by talentAN** [comment]
> Your server version is too old, this issue has been fixed by updating gui/server.

repeat:

{"id":"b19f588a7d4e11eaacd30242ac110006","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point, avg(total_amount) AS w FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-94.55232097143656 19.211495627778902, -94.55232097143656 56.98325825991088, -53.33161784643667 56.98325825991088, -53.33161784643667 19.211495627778902, -94.55232097143656 19.211495627778902))'))) GROUP BY point","type":"heat","params":{"width":938,"height":1139,"heat":{"bounding_box":[-94.55232097143656,19.211495627778902,-53.33161784643667,56.98325825991088],"coordinate_system":"EPSG:4326","map_zoom_level":4,"aggregation_type":"avg"}}}}
