### ISSUE TITLE
PointMap draw circle filter not accurate

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#487]
{"id":"b19f588a7d4e11eaacd30242ac110006","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-74.00331882354796 40.73173437747056, -74.00331882354796 40.756688975279644, -73.95445633238755 40.756688975279644, -73.95445633238755 40.73173437747056, -74.00331882354796 40.73173437747056))'))) AND ((ST_Distance(ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude),'epsg:4326', 'epsg:3857'),st_transform(st_geomFromText ('point(-73.9857125008224 40.75176874045121)'),'epsg:4326', 'epsg:3857')) < 554.6974227907358) OR (ST_Distance(ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude),'epsg:4326', 'epsg:3857'),st_transform(st_geomFromText ('point(-73.99135048057163 40.74097791358824)'),'epsg:4326', 'epsg:3857')) < 665.6923349429152)) LIMIT 1000000","type":"point","params":{"width":494,"height":332,"point":{"opacity":0.5,"bounding_box":[-74.00331882354796,40.73173437747056,-73.95445633238755,40.756688975279644],"coordinate_system":"EPSG:4326","point_size":3,"point_color":"#37A2DA"}}}}

![image](https://user-images.githubusercontent.com/17634030/79103225-c7e1f300-7d9e-11ea-9e59-8c645c36a8f2.png)

**Comment by bigsheeper** [comment]
We don't recommend to add ST_within filter together with ST_Distance, in case of increasing the unnecessary time.

**Comment by talentAN** [comment]
> It's not recommended to add ST_within filter together with ST_Distance, in case of increasing unnecessary runtime.

then what if the filters contain both st_within and st_distance?

**Comment by bigsheeper** [comment]
Just using st_distance filter can get the same result. If you did a ST_Distance operation, there is no necessary to do ST_Within any more. ST_Distance can filter the data which you want to filter in ST_Within. So, here, ST_Within is redundant.

**Comment by bigsheeper** [comment]
I did a test for this issue:
1. Create a circle to draw a point map in this circle:
```
{"id":"f7a853487e3611eab13704d4c4a9870c","query":{"sql":"SELECT ST_Point (dropoff_longitude, dropoff_latitude) AS point FROM nyc_taxi WHERE (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText('POLYGON ((-74.02483010382888 40.69162819372934, -74.02483010382888 40.72118024827043, -74.00048287051021 40.72118024827043, -74.00048287051021 40.69162819372934, -74.02483010382888 40.69162819372934))'))) AND ((ST_Distance(ST_Transform (ST_Point (dropoff_longitude, dropoff_latitude),'epsg:4326', 'epsg:3857'),st_transform(st_geomFromText ('point(-74.01511667798366 40.701298738762546)'),'epsg:4326', 'epsg:3857')) < 861.7035689519278)) AND ((buildingtext_dropoff!='')) LIMIT 1000000000","type":"point","params":{"width":692,"height":1107,"point":{"opacity":0.5,"bounding_box":[-74.02483010382888,40.69162819372934,-74.00048287051021,40.72118024827043],"coordinate_system":"EPSG:4326","point_size":7.59,"point_color":"#37A2DA"}}}}
```
2. Get the 'point(-74.01511667798366 40.701298738762546)' params in sql, apparently  it's the centre of the circle.
3. Choose a farthest point in the map, and do a ST_Distance operation to calculate the distance between this point and center point, here is the sql and test result:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|ST_Distance(ST_Transform(ST_GeomFromText(POINT(-74.009813 40.705505)), epsg:4326, epsg:3857), ST_Transform(ST_GeomFromText(point(-74.01511667798366 40.701298738762546)), epsg:4326, epsg:3857))|
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|854.4405793381909                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
The result 854 is very close to 861.7035689519278 in the request sql.  
  

4. Choose a point on the edge of the circle, and also calculate the distance between this point and center point, here is the sql and test result:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|ST_Distance(ST_Transform(ST_GeomFromText(POINT(-74.009753 40.708003)), epsg:4326, epsg:3857), ST_Transform(ST_GeomFromText(point(-74.01511667798366 40.701298738762546)), epsg:4326, epsg:3857))|
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|1151.3926325398108                                                                                                                                                                              |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
The result 1151 is greater than 861.7035689519278.
  

Conclusion: Render engine return the right result I request, the problem is that the circle from the front end is bigger than I thought.
