### ISSUE TITLE
choroplethmap sql without ST_Within

### ISSUE THREAD

**Issue by xge-zilliz** [zilliztech/arctern#512]
tthe web sql like this:
{"id":"4785ef8080ab11ea969604d4c4a9871a","query":{"sql":"SELECT ST_GeomFromText(buildingtext_pickup) AS wkt, avg(total_amount) AS w FROM nyc_taxi WHERE ((buildingtext_pickup!='')) GROUP BY wkt","type":"choropleth","params":{"width":1922,"height":1663,"choropleth":{"bounding_box":[-74.03488380223871,40.711070838295456,-73.94028441078791,40.78222122805914],"coordinate_system":"EPSG:4326","color_gradient":["#115f9a","#d0f400"],"color_bound":[5,18],"opacity":1,"aggregation_type":"avg"}}}}

suggesstion:
SELECT ST_GeomFromText(buildingtext_pickup) AS wkt, avg(total_amount) AS w FROM nyc_taxi WHERE ((buildingtext_pickup!='')) AND ST_Within (ST_GeomFromText(buildingtext_pickup), ST_GeomFromText('POLYGON ((-74.03488380223871 40.711070838295456, -74.03488380223871 40.78222122805914, -73.94028441078791 40.78222122805914, -73.94028441078791 40.711070838295456, -74.03488380223871 40.711070838295456))'))) GROUP BY wkt

**Comment by talentAN** [comment]
@xge-zilliz  done, pls check

SELECT
  ST_GeomFromText (buildingtext_dropoff) AS wkt,
  avg(tip_amount) AS w
FROM
  nyc_taxi
WHERE (buildingtext_dropoff != '')
  AND (ST_Within (ST_Point (dropoff_longitude, dropoff_latitude), ST_GeomFromText ('POLYGON ((-74.00872834702899 40.72841115742682, -74.00872834702899 40.74902859656174, -73.97277414795855 40.74902859656174, -73.97277414795855 40.72841115742682, -74.00872834702899 40.72841115742682))')))
GROUP BY
  wkt



SELECT
  ST_GeomFromText (buildingtext_dropoff) AS wkt,
  avg(tip_amount) AS w
FROM
  nyc_taxi
WHERE (buildingtext_dropoff != '')
  AND ((ST_DistanceSphere (ST_Point (dropoff_longitude, dropoff_latitude), st_geomFromText ('point(-73.99156838838202 40.74184727097759)')) < 443.0141112140629))
GROUP BY
  wkt
