### ISSUE TITLE
ST_GeomFromText run error

### ISSUE THREAD

**Issue by xge-zilliz** [zilliztech/arctern#538]
>>> region = pd.read_csv("data.csv", dtype={'geos':np.object})

data.csv only one column of polygons, like "POLYGON ((113.66220266388723 22.39277623851494, 114.58136061218778 22.39277623851494, 114.58136061218778 22.92800492531275 ,113.66220266388723 22.92800492531275, 113.66220266388723 22.39277623851494))"

>>> res= arctern.ST_GeomFromText(region['geos'])

when data.csv has 10000000 rows of data, the Statement "arctern.ST_GeomFromText(region['geos'])" runs successfully, but when data.csv has 20000000 rows of data, run error info "Segmentation fault (core dumped)"

**Comment by nezha2017** [comment]
this is fix on #539
