### ISSUE TITLE
PointMap unexpedted runder

### ISSUE THREAD

**Issue by talentAN** [zilliztech/arctern#550]
{"id":"8be673d2890411ea8b7e000d3a81595b","query":{"sql":"SELECT ST_Point (longitude, latitude) AS point, cityCurrentConfirmedCount AS color, cityConfirmedCount AS size FROM china WHERE (ST_Within (ST_Point (longitude, latitude), ST_GeomFromText('POLYGON ((-5.256275292125309 -85.05112899999992, -5.256275292125309 85.05112900000003, 213.44455123091348 85.05112900000003, 213.44455123091348 -85.05112899999992, -5.256275292125309 -85.05112899999992))'))) LIMIT 1000000","type":"weighted","params":{"width":664,"height":1093,"weighted":{"opacity":1,"bounding_box":[-5.256275292125309,-85.05112899999992,213.44455123091348,85.05112900000003],"coordinate_system":"EPSG:4326","size_bound":[1,16],"color_bound":[-1,75],"color_gradient":["#4d904f","#c23728"]}}}}

return an empty image which is not expected

**Comment by xge-zilliz** [comment]
Why is the value of longitude greater than 180? @talentAN

**Comment by nezha2017** [comment]
https://epsg.io/3857,for the usage area of `EPSG 3857` is `between 85.06°S and 85.06°N.`
If the longitude is greater than 180, subtract 360 from this value.

the one of the  `longitude` in this issue is `213.44455123091348`, so replace this value with `213.44455123091348 - 360 = -146.55544876908652`

**Comment by talentAN** [comment]
> https://epsg.io/3857,for the usage area of `EPSG 3857` is `between 85.06°S and 85.06°N.`
> If the longitude is greater than 180, subtract 360 from this value.
> 
> the one of the `longitude` in this issue is `213.44455123091348`, so replace this value with `213.44455123091348 - 360 = -146.55544876908652`
