### ISSUE TITLE
Fail to install arctern due to incompatible packages.

### ISSUE THREAD

**Issue by RyanWei** [zilliztech/arctern#565]
**Describe the bug**
Fail to install arctern, can you help?

**To Reproduce**
(arctern_python) [milvus@sol01:~]$ conda activate arctern_python
(arctern_python) [milvus@sol01:~]$ conda install -c arctern libarctern
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                              failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package tk conflicts for:
python=3.7 -> tk[version='>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package zlib conflicts for:
python=3.7 -> zlib[version='>=1.2.11,<1.3.0a0']
Package readline conflicts for:
python=3.7 -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']
Package xz conflicts for:
python=3.7 -> xz[version='>=5.2.4,<6.0a0']
Package gdal conflicts for:
libarctern -> gdal==3.0.4
Package ld_impl_linux-64 conflicts for:
python=3.7 -> ld_impl_linux-64
Package ncurses conflicts for:
python=3.7 -> ncurses[version='>=6.1,<7.0a0|>=6.2,<7.0a0']
Package libgcc-ng conflicts for:
python=3.7 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package openssl conflicts for:
python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a']
Package sqlite conflicts for:
python=3.7 -> sqlite[version='>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0']
Package libffi conflicts for:
python=3.7 -> libffi[version='>=3.2.1,<3.3a0']
Package libstdcxx-ng conflicts for:
python=3.7 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
Package rapidjson conflicts for:
libarctern -> rapidjson==1.1.0
Package pip conflicts for:
python=3.7 -> pip
Package pyarrow conflicts for:
libarctern -> pyarrow=0.16.0
Package libnetcdf conflicts for:
libarctern -> libnetcdf[version='4.7.3,>=4.7.3,<5.0a0']

**Comment by nezha2017** [comment]
1. remove `arctern_python`
```bash
conda env remove -n arctern_python
```
2. recreate with this command
```bash
conda create -n arctern_python -c conda-forge  python=3.7.6
```
3.
```bash
conda activate arctern_python
```
4. install arctern
```bash
conda install -c arctern -c conda-forge  libarctern
 conda install -c arctern -c conda-forge arctern
```
