### ISSUE TITLE
Return data with incorrect data type series when input data has None value

### ISSUE THREAD

**Issue by shengjh** [zilliztech/arctern#572]
**Describe the bug**
For python wrapper functions which return type is bool data type series , it return object type series with None value, when input data has None value. Such as ST_IsSimple,  ST_IsValid.

**To Reproduce**
1. Create invalid geometries.
2. Use St_IsValid to check geometries is valid 
```python
    s = arctern.ST_GeomFromText(["point(1 2)", "point(1)"])
    print(arctern.ST_IsValid(s))
```

**Expected behavior**
The result should be a series with bool data type, specially for None geometry is False.

**Any logs, error output, snapshot, etc?**
Here are output for above code. Each item in series is object type.
0    True
1    None
dtype: object

**Software versions:**
 - Arctern: Branch 0.1.x

**Comment by nezha2017** [comment]
It is reasonable to return `null` if input is `null` for the `sql` expression.

**Comment by shengjh** [comment]
In most instances，return null is reasonable.  Here we want to check a geometry is valid or not, maybe return false for null geometry more properly?

**Comment by nezha2017** [comment]
> In most instances，return null is reasonable. Here we want to check a geometry is valid or not, maybe return false for null geometry more properly?

`None` means `False` in python, so return is reasonable
```python
>>> if None:
...     print("hello")
... else:
...     print("world")
... 
world
```

**Comment by shengjh** [comment]
Maybe I need to reopen this, let me explain why False is needed rather than None. @nezha2017 
Consider this code:
```
import arctern
s = arctern.ST_GeomFromText(["point(1 2)", "point(1)"])
s_valid = s[arctern.ST_IsValid(s)]
print(s_valid)
```
The code want to get the valid  geometry in s, and print it. But It will be failed since pandas think get_item with a invalid bool index.
Error msg can be like this:
```
    s_valid = s[arctern.ST_IsValid(s)]
  File "/home/shengjh/miniconda3/envs/arctern/lib/python3.8/site-packages/pandas/core/series.py", line 907, in __getitem__
    if com.is_bool_indexer(key):
  File "/home/shengjh/miniconda3/envs/arctern/lib/python3.8/site-packages/pandas/core/common.py", line 136, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values
```

So if i want to make it works, i have to add a 'astype()' for ST_IsValid.
```
s = arctern.ST_GeomFromText(["point(1 2)", "point(1)"])
    s_valid = s[arctern.ST_IsValid(s).astype(bool)]
    print(s_valid)
```

**Comment by nezha2017** [comment]
@shengjh , in the `SQL`, every operation with `null` will return `null`,for example
```sql
(zgis_dev) ➜  sqlite3
SQLite version 3.30.1 2019-10-10 20:19:45
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> create table t(a int ,b int);
sqlite> insert into t values(1,2);
sqlite> insert into t values(null,3);
sqlite> select * from t;
1|2
|3
sqlite> select a>b from t;
0

sqlite> 
```

```bash
>>> s = arctern.ST_GeomFromText(pandas.Series(["point(1 2)", "point(1)"]))
>>> s
0    b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00...
1                                                 None
dtype: object
```
so the operation on `s[1]` will return `null`.

what's your opinion @GuoRentong

**Comment by shengjh** [comment]
I missed that arctern python wrapper function aimed to working for `SQL` statment at the begging. 
So it would be still None better when operation on missing value.
Recently i am trying to wrapper all python api to a GeoSeries(extend pandas Series). It will translate None value to False in some operation, e.g. ST_IsValid.
Going to close this issue.
