### ISSUE TITLE
lost  index in python wrapper function api result

### ISSUE THREAD

**Issue by shengjh** [zilliztech/arctern#583]
**Describe the bug**
Currently python api input data is pandas series, and output data is series. For series we can access items with user defined index. The bug is when input data is series with customized index, the output series will have Inconsistent index.

**To Reproduce**
Steps to reproduce the behavior
Test code:
```
s = Series(["point(1 2)", "point(2, 3)"], index=['a', 'b'])
rst = arctern.ST_GeomFromText(s)
print(rst['a'])
```

**Expected behavior**
Don't raise exception, and can use s.index to access rst.

**Any logs, error output, snapshot, etc?**
Code above will raise exception.
```
File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 90, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 135, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 109, in pandas._libs.index.Int64Engine._check_type
KeyError: 'a'
```

**Software versions:**
 - Arctern: Branch master

**Comment by nezha2017** [comment]
the default index is a list from 0 until `length_of_series`, this is the test code.
```python
>>> import pandas
>>> p1=pandas([10,11,12])
>>> p2=pandas.Series([13,14,15])
>>> p3=p1.append(p2)
>>> p3.index
Int64Index([0, 1, 2, 0, 1, 2], dtype='int64')
>>> p3[0]
0    10
0    13
dtype: int64
>>> p4=p1.append(p2,ignore_index=True)
>>> p4.index
RangeIndex(start=0, stop=6, step=1)
```
if the input series has default index, the output data would have duplicated index, so we ignore the input index before construct the output.

**Comment by shengjh** [comment]
Python wrapper function api will not support index, and 
index is supported in arctern.GeoSeries, here is a example:
```
s = pd.Series(["POINT(1 1)"], index=['a'])
s1  = GeoSeries(s)
print(s1)
```
Output is:
```
a    POINT (1 1)
dtype: GeoDtype
```
Note s1 have same index with s.
