### ISSUE TITLE
Spark not work, gis function crashed

### ISSUE THREAD

**Issue by bigsheeper** [zilliztech/arctern#602]
**Describe the bug**
I follow the instruction in installation doc <https://arctern.io/docs/versions/v0.1.x/arctern-webdocs/development-doc-cn/html/spark/installation_and_deployment/install_arctern_on_spark_cn.html>
After running the `spark_udf_ex.py`, spark crashed.
I'v made this test in server machine—zilliz_support@192.168.1.85

**To Reproduce**
1. install arctern 
2. download spark-3.0.0-preview2-bin-hadoop2.7
3. config spark
4. run spark_udf_ex.py

**Expected behavior**
All tests of arctern have passed!

**Any logs, error output, snapshot, etc?**
[spark_log.txt](https://github.com/zilliztech/arctern/files/4620266/spark_log.txt)

**Software versions:**
 - OS: Ubuntu, server machine—zilliz_support@192.168.1.85
 - Arctern: 0.1.1

**Comment by nezha2017** [comment]
set `JAVA_HOME` to `java8`
