### ISSUE TITLE
koalas geoseries distance_sphere

### ISSUE THREAD

**Issue by czpmango** [zilliztech/arctern#852]
**Describe the bug**
koalas geoseries distance_sphere got different result with postgis.

**To Reproduce**
koalas geoseries test :
```python
>>> from arctern_spark.geoseries import GeoSeries
>>> from databricks.koalas import Series
>>> s1 = GeoSeries(['LINESTRING ( 60 50, 70 50, 70 60, 10 60, 60 50 )'])
>>> s2 = GeoSeries(['MULTIPOINT (3 4)'])
>>> s1.set_crs('EPSG:4326')
>>> s2.set_crs('EPSG:4326')
>>> s1.distance_sphere(s2)
0   NaN
Name: 0, dtype: float64

```
---
postgis test:
```sql
postgres=# select st_distance_sphere('SRID=4326;LINESTRING ( 60 50, 70 50, 70 60, 10 60, 60 50 )','SRID=4326;MULTIPOINT (3 4)');
WARNING:  ST_Distance_Sphere signature was deprecated in 2.2.0. Please use ST_DistanceSphere
 st_distance_sphere 
--------------------
   6255452.47205575
(1 row)

```

**Expected behavior**
Expect the same results with postgis.

**Comment by bigsheeper** [comment]
ST_DistanceSphere function can only calculate the distance between two points.
Illegal geoemtries or illegal EPSG:4326 coordinates will get the Nan result.

**Comment by czpmango** [comment]
> ST_DistanceSphere function can only calculate the distance between two points.
> Illegal geoemtries or illegal EPSG:4326 coordinates will get the Nan result.

Got it.

**Comment by czpmango** [comment]
I realized that ST_Distance_sphere can only calculate coordinate values in range [-180 -90, 180 90] for GEOGRAPHY, but when I use `POINT(100 50)` as the input, the output is Nan, which is not what I expected.

**Comment by czpmango** [comment]
postgis warning is like this : ` NOTICE:  Coordinate values were coerced into range [-180 -90, 180 90] for GEOGRAPHY `

**Comment by czpmango** [comment]
Already fixed.
